import com.jeffy.droolsapp.models.Entity;
import com.jeffy.droolsapp.models.Dcr;
import com.jeffy.droolsapp.models.RoutingInfo;

dialect  "mvel"

rule "Route Dcr - Country US to internal"
    when
    	r: RoutingInfo()
    	dcr: Dcr(entity.country=="US")
    then
      	modify(r) {
      		routeTo = "internal"
      	}
      	modify(dcr) {
      		destination = "internal"
      	}
end


rule "Route Dcr - Country NOT US to external"
    when
    	r: RoutingInfo()
    	dcr: Dcr(entity.country !="US")
    then
      	modify(r) {
      		routeTo = "external"
      	}
      	modify(dcr) {
      		destination = "external"
      	}
end